{
 "title": "Pocket Nodes",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Relays for all Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"pocketcore_service_relay_count_for_0(.*)\"}, \"chain\", \"$1\", \"__name__\", \"pocketcore_service_relay_count_for_0(.*)\")[$__rate_interval:])\n\n",
     "legendFormat": "{{chain}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Load (1 min)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"node-exporter:9100\"}",
     "legendFormat": "Load (5 min)"
    }
   ]
  },
  {
   "title": "Load (5 min)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{instance=\"node-exporter:9100\"}",
     "legendFormat": "Load (5 min)"
    }
   ]
  },
  {
   "title": "Load (15 min)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load15{instance=\"node-exporter:9100\"}",
     "legendFormat": "Load (5 min)"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user'}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait'}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle'}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Avg Relay Time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pocketcore_service_avg_relay_time_for_0001_sum) / sum(pocketcore_service_avg_relay_time_for_0001_count)",
     "legendFormat": "POKT"
    },
    {
     "expr": "sum(pocketcore_service_avg_relay_time_for_0009_sum) / sum(pocketcore_service_avg_relay_time_for_0009_count)",
     "legendFormat": "Polygon"
    },
    {
     "expr": "sum(pocketcore_service_avg_relay_time_for_0021_sum) / sum(pocketcore_service_avg_relay_time_for_0021_count)",
     "legendFormat": "ETH"
    },
    {
     "expr": "sum(pocketcore_service_avg_relay_time_for_0027_sum) / sum(pocketcore_service_avg_relay_time_for_0027_count)",
     "legendFormat": "Gnosis"
    },
    {
     "expr": "sum(pocketcore_service_avg_relay_time_for_0040_sum) / sum(pocketcore_service_avg_relay_time_for_0040_count)",
     "legendFormat": "Harmony One"
    },
    {
     "expr": "sum(pocketcore_service_avg_relay_time_for_03DF_sum) / sum(pocketcore_service_avg_relay_time_for_03DF_count)",
     "legendFormat": "DeFi Kingdoms"
    },
    {
     "expr": "sum(pocketcore_service_avg_relay_time_for_03CB_sum) / sum(pocketcore_service_avg_relay_time_for_03CB_count)",
     "legendFormat": "Swimmer"
    },
    {
     "expr": "sum(pocketcore_service_avg_relay_time_for_0003_sum) / sum(pocketcore_service_avg_relay_time_for_0003_count)",
     "legendFormat": "AVAX"
    },
    {
     "expr": "sum(pocketcore_service_avg_relay_time_for_0049_sum) / sum(pocketcore_service_avg_relay_time_for_0049_count)",
     "legendFormat": "Fantom"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit", "label": "%util" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Load Avg",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 19 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load Avg (1 min)" },
    { "expr": "node_load5", "legendFormat": "Load Avg (5 min)" },
    { "expr": "node_load15", "legendFormat": "Load Avg (15 min)" }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"pokt-000:8083\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "process_open_fds{instance=\"pokt-001:8083\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Pressure",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total{}[$__rate_interval])",
     "legendFormat": "CPU Wait"
    },
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{}[$__rate_interval])",
     "legendFormat": "I/O Wait"
    },
    {
     "expr": "rate(node_pressure_io_stalled_seconds_total{}[$__rate_interval])",
     "legendFormat": "I/O Stalled"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(pocketcore_service_sessions_count_for_all[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(pocketcore_service_err_count_for_all[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}